### ISSUE TITLE
 When used with Reactive Navigation, there is gap between keyboard and renderContent.

### ISSUE THREAD

**Issue by aksmfosef11** [wix/react-native-keyboard-input#80]
When loading the first page, nothing is wrong.
However, if  I go to another screen using `navigate` in `ReactNavigation` and then use `goBack` to return to the page with keyboard-input, there will be a gap between keyboard and `renderContent`.

firstLoading
![before](https://user-images.githubusercontent.com/37918339/62031047-6b936f00-b221-11e9-88c3-5ea86291c3f8.png)

after goBack
![after](https://user-images.githubusercontent.com/37918339/62031053-6e8e5f80-b221-11e9-85d5-f0de146e7bb0.png)

**Comment by aksmfosef11** [comment]
Fixed by modifying `KeyboardTrackingView` in xcode.
I do not know why, but after using `goBack` `[notification.userInfo [UIKeyboardFrameEndUserInfoKey] CGRectValue];` The value of

I Changed `- (void)_keyboardWillChangeFrameNotification:(NSNotification*)notification` to 
```
- (void)_keyboardWillChangeFrameNotification:(NSNotification*)notification
{
    if(self.window)
    {
        return;
    }
    
    CGRect endFrame = [notification.userInfo[UIKeyboardFrameEndUserInfoKey] CGRectValue];
    CGRect beginFrame = [notification.userInfo[UIKeyboardFrameBeginUserInfoKey] CGRectValue];
    if (endFrame.origin.y > beginFrame.origin.y) {
        _keyboardHeight = [UIScreen mainScreen].bounds.size.height - endFrame.origin.y;
    }else {
        _keyboardHeight = [UIScreen mainScreen].bounds.size.height - beginFrame.origin.y;
    }

    [_delegate observingInputAccessoryViewDidChangeFrame:self];
    
	[self invalidateIntrinsicContentSize];
}

```


I hope this helps people with similar problems.

**Comment by oferRounds** [comment]
@aksmfosef11  seeing the same problem, and tried your solution, but the problem still persists. Any idea?

**Comment by djorkaeffalexandre** [comment]
This problem is related to Tracking the wrong TextInput, you need to reset Tracking when the screen get focus. To reset tracking you can use `[self deferedInitializeAccessoryViewsAndHandleInsets];`.

**Comment by oferRounds** [comment]
@djorkaeffalexandre thank you!
Although not I understand, can you show how – where do I add this line? This seems related only to iOS
